#ifndef DEFINES_HEADER
#define DEFINES_HEADER
#pragma comment(lib, "legacy_stdio_definitions.lib")
#pragma comment(lib, "..\\hgelibs\\lib\\vc\\hge.lib")
#pragma comment(lib, "..\\hgelibs\\lib\\vc\\hgehelp.lib")

//MAIN
#define SCREEN_RESOLUTION_X 448
#define SCREEN_RESOLUTION_Y 480

//SCORE DATA
#define SCORE_EACH_STEP 10
#define SCORE_FROG_HOME 480
#define SCORE_PICKUP_BUG 1000

//TIME
#define TIME_FOR_EACH_FROG 25

//FROG DATA
#define WALK_TIME 0.15f
#define WALK_SPEED 200.0f
#define DEATH_TIMER 0.3f
#define RESPAWN_TIME 1.0f
#define NR_OF_LIVES 4
#define WALK_COOLDOWN 0.04f

//BUG DATA
#define TIME_BETWEEN_BUG_SPAWNS 4.0f
#define TIME_FOR_BUG_TO_STAY 2.0f

//GRID DATA
#define GRIDSIZE_X 14
#define GRIDSIZE_Y 13
#define TILESIZE 32.0f

//VEHICLE DATA
enum VehicleTypes
{
	CAR,
	BULLDOZER,
	FERARRI,
	TRUCK,
	BUS,

	NUM_VEHICLE_TYPES,
};

//CAR
#define CAR_START_POS_X TILESIZE*(GRIDSIZE_X+1)
#define CAR_START_POS_Y (12 * TILESIZE) - TILESIZE * 0.5f

//BULLDOZER
#define BULLDOZER_START_POS_X -32.0f
#define BULLDOZER_START_POS_Y (11 * TILESIZE) - TILESIZE * 0.5f

//FERARRI
#define FERARRI_START_POS_X TILESIZE*(GRIDSIZE_X+1)
#define FERARRI_START_POS_Y (10 * TILESIZE) - TILESIZE * 0.5f

//TRUCK
#define TRUCK_START_POS_X -32.0f
#define TRUCK_START_POS_Y (9 * TILESIZE) - TILESIZE * 0.5f

//BUS
#define BUS_START_POS_X TILESIZE*(GRIDSIZE_X+1)
#define BUS_START_POS_Y (8 * TILESIZE) - TILESIZE * 0.5f

//WATER ENTITY DATA
enum WaterEntityTypes
{
	BIG_TURTLE,
    SMALL_TURTLE,
	SMALL_LOG,
    MEDIUM_LOG,
    BIG_LOG,

	NUM_WATER_ENTITY_TYPES,
};

//SMALL_TURTLE
#define SMALL_TURTLE_START_POS_X TILESIZE*(GRIDSIZE_X+1)
#define SMALL_TURTLE_START_POS_Y (3 * TILESIZE) - TILESIZE * 0.5f

//BIG_TURTLE
#define BIG_TURTLE_START_POS_X TILESIZE*(GRIDSIZE_X+1)
#define BIG_TURTLE_START_POS_Y (6 * TILESIZE) - TILESIZE * 0.5f

//SMALL_LOG
#define SMALL_LOG_START_POS_X -128.0f
#define SMALL_LOG_START_POS_Y (5 * TILESIZE) - TILESIZE * 0.5f

//MEDIUM_LOG
#define MEDIUM_LOG_START_POS_X -128.0f
#define MEDIUM_LOG_START_POS_Y (2 * TILESIZE) - TILESIZE * 0.5f

//BIG_LOG
#define BIG_LOG_START_POS_X -128.0f
#define BIG_LOG_START_POS_Y (4 * TILESIZE) - TILESIZE * 0.5f

#endif